# Generated by Django 4.2.3 on 2023-07-25 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="video_url",
            new_name="file",
        ),
        migrations.RemoveField(
            model_name="video",
            name="time",
        ),
        migrations.AddField(
            model_name="video",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
