# Generated by Django 4.2.3 on 2023-07-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0002_rename_video_url_video_file_remove_video_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
