# Generated by Django 4.2.3 on 2023-07-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0003_alter_video_description_alter_video_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.FileField(
                upload_to="mp4s/<django.db.models.fields.CharField>"
            ),
        ),
    ]
