# Generated by Django 4.2.3 on 2023-07-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0004_alter_video_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.FileField(upload_to="mp4s/"),
        ),
    ]
